#ifndef ERROS_H_INCLUDED
#define ERROS_H_INCLUDED

typedef enum{
    ERRO_OK = 0,

    // Memória
    ERRO_MEMORIA,

    // Usuários
    ERRO_USUARIO_EXISTE,
    ERRO_USUARIO_NAO_ENCONTRADO,

    // Hash
    ERRO_HASH_COLISAO_FALHOU,
    ERRO_HASH_MEMORIA,
    ERRO_HASH_INSERCAO_FALHOU,

    // AVL
    ERRO_AVL_CHAVE_DUPLICADA,
    ERRO_AVL_MEMORIA,
    ERRO_AVL_INSERCAO_FALHOU,
    ERRO_AVL_NO_NAO_ENCONTRADO,
    ERRO_AVL_DUPLICADO,

    // Lista
    ERRO_LISTA_MEMORIA,
    ERRO_LISTA_NO_MEMORIA,
    ERRO_LISTA_NO_NAO_ENCONTRADO,


    // Geral
    ERRO_DESCONHECIDO,

    ERRO_PARAMETRO_INVALIDO,
    ERRO_EMAIL_NAO_ENCONTRADO,
    ERRO_SISTEMA_NAO_INICIADO,
    ERRO_LOGIN_SUCESSO,
    ERRO_LOGIN_FALHOU,

}CodigoErro;

const char* CodigoErroParaTexto(CodigoErro erro) ;



#endif // ERROS_H_INCLUDED
